### ISSUE TITLE
instrucntion not clear

### ISSUE THREAD

**Issue by muafakul** [kan2k/Spark-AR-Physic-based-3D-Game#2]
Go to the patch editor and choose whether to start with recording/tap screen.
All the codes are in script.js

I fail .i dont know where to connect

**Comment by kan2k** [comment]
please check the new instruction

**Comment by stickylabdev** [comment]
thanks a lot ,,,,,,,,,,,,

**Comment by stickylabdev** [comment]
by the way ,, i hope you make another game :D ,,,
